USE [master]
ALTER DATABASE [BlogManSysAuthDb] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
BACKUP LOG [BlogManSysAuthDb] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\BlogManSysAuthDb_LogBackup_2023-11-15_14-49-21.bak' WITH NOFORMAT, NOINIT,  NAME = N'BlogManSysAuthDb_LogBackup_2023-11-15_14-49-21', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [BlogManSysAuthDb] FROM  DISK = N'C:\Daten\Hassan\Code\Blog Managment System\Blog managment system\database\AuthDB.bak' WITH  FILE = 2,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [BlogManSysAuthDb] SET MULTI_USER
GO

USE [master]
ALTER DATABASE [BlogManSysDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
BACKUP LOG [BlogManSysDB] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\BlogManSysDB_LogBackup_2023-11-15_14-50-16.bak' WITH NOFORMAT, NOINIT,  NAME = N'BlogManSysDB_LogBackup_2023-11-15_14-50-16', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [BlogManSysDB] FROM  DISK = N'C:\Daten\Hassan\Code\Blog Managment System\Blog managment system\database\DB.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [BlogManSysDB] SET MULTI_USER

GO

